### ISSUE TITLE
Google TTS - Cannot connect

### ISSUE THREAD

**Issue by MisterInsane** [medokin/soundpad-text-to-speech#19]
I enabled the API and created the OAuth ID credentials and downloaded the JSON file.

I pasted the JSON file in and got the following error in the log.

2022-07-08 19:28:02,254 [3] ERROR TTSGoogle.GoogleSpeechToTextProvider - Cannot connect to Google
System.InvalidOperationException: Error creating credential from JSON. Unrecognized credential type .
   at Google.Apis.Auth.OAuth2.DefaultCredentialProvider.CreateDefaultCredentialFromParameters(JsonCredentialParameters credentialParameters)
   at Google.Apis.Auth.OAuth2.DefaultCredentialProvider.CreateDefaultCredentialFromJson(String json)
   at TTSGoogle.GoogleSpeechToTextProvider.get_Client()
   at TTSGoogle.GoogleSpeechToTextProvider.<CheckAvailable>d__13.MoveNext()

**Comment by ashenbeauty** [comment]
I'm currently unable to use Google TTS as well. Attached is a paste of my log upon an attempt to select Google as my provider. Attempting shows a "Provider is not available" error box. My JSON auth previously worked, and this issue seems to have cropped up recently, within the past month.
[7-16-2023.log](https://github.com/medokin/soundpad-text-to-speech/files/12066101/7-16-2023.log)

**Comment by xrayman123** [comment]
Sir @medokin I am sorry to ping you I don't know if it's against the rules... but I am not code savvy and I have really been trying for days to do this.

@CailanVR @MisterInsane  was anyone able to sort it?

This is my 1st post in like 15 years 2024 And people are prob still struggling. a dummy walk-through would be nice. this is what I have done:

1. Downloaded Google Cloud SDK CMD 
2. Made a Google https://console.cloud.google.com/ account and made a project just for Google TTS
- Enabled installed Google TTS API
- Made Service Account credentials
- Downloaded API key
3. Down and install Go lang in Google SDK CMD from https://go.dev/dl/ - go1.23.1
4. Put the below into Google SDK CMD
- gcloud init
- gcloud auth application-default login
- go install cloud.google.com/go/texttospeech/apiv1@latest
-  **_*side note: when I do this it says "package cloud.google.com/go/texttospeech/apiv1 is not a main package" _**
5. Put downloaded API key JSON using Notepad ++ Copy and paste into settings
6. Restart TTS
7. Click provider... Grayed out...
8. IDK WHAT TO DOOOOOO I've been pulling my hair out for days....
9. GIVE UP
